import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Typography } from '@mui/material'
import Home from './Home'
import Footer from './Footer'
import Contact from './Contact'

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Iftakher Hossen - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Home />
        <Contact />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  )
}
